### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by thiagones** [nicopastorello/SeleniumFbAutomation#1]
Boa tarde, Nico!
Tudo joia?

Nico, estou pensando em fazer algo parecido para automatizar postagens no facebook.
Alguma vez você já sofreu alguma penalidade pelas postagens estarem sendo feitas por um robô?

Muito obrigado!
Att.

**Comment by nicopastorello** [comment]
Bom dia, Thiago!

Infelizmente no decorrer do uso do meu script já acontecera, punições e banimentos e pedidos de troca de senha, atualmente no estado atual dele faz alguns meses que não sofri mais penalidades mas como se trata de um script o Facebook poderá identificar como um "robo" mesmo configurando com random.

**Comment by thiagones** [comment]
Muito obrigado, Nico!
